### ISSUE TITLE
code for plots

### ISSUE THREAD

**Issue by bowerth** [sebastiansauer/modar#1]
hello - would it be possible to provide the code for the plots in `static/images`?

**Comment by sebastiansauer** [comment]
Sure, check out whether this link covers all you need: http://www.springer.com/cda/content/document/cda_downloaddocument/Abbildungen.zip?SGWID=0-0-45-1650025-p181556499

**Comment by sebastiansauer** [comment]
Oh sorry, you mean the code, not the images. Most of the code is in the book, I think. Have you checked that out? Otherwise, please check out whether it's in here (I think it is): http://www.springer.com/cda/content/document/cda_downloaddocument/R-Syntax.zip?SGWID=0-0-45-1648817-p181556499

**Comment by bowerth** [comment]
thank you, this seems to include all the code snippets required to reproduce the plots
