### ISSUE TITLE
Lösung Deskriptive Statistik

### ISSUE THREAD

**Issue by Cupidshuffle** [sebastiansauer/modar#2]
Hallo,
zu den Aufgaben auf Seite 114 gibt´s "nur" 9 Lösungen - aber 10 Fragen.
Ich bin mir nicht sicher, ob die Lösung für die Aufgabe 9 oder 10 vergessen wurde. Ich hätte nämlich gesagt, dass die 9 ein 'F' sein müsste und 10 ein 'R' ist.

Wie lautet denn die Lösung? :-)

**Comment by NMarkgraf** [comment]
In der Tat! 

1. Richtig
2. Richtig
3. Richtig
4. Falsch, vgl. https://stackoverflow.com/questions/31412514/na-values-not-being-excluded-in-cor/31412568
5. Falsch
6. Falsch
7.  Falsch
8. Richtig 
9. Falsch
10. Richtig

Danke für den Hinweis!

**Comment by Cupidshuffle** [comment]
Alles klar, danke dafür!
